name: dig_text_similarity
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.6
  - faiss-cpu
  - pip:
    - happybase>=1.1.0
    - numpy
    - tensorflow_hub
    - Flask
    - Flask-API
    - flask-cors
    - requests
    - tensorflow
    - pandas
    - ipykernel
    - jupyter
